version: "3.8"

services:
  # 1) Le scheduler Dask
  scheduler:
    image: daskdev/dask:latest
    command: dask-scheduler
    ports:
      - "8786:8786"   # port RPC
      - "8787:8787"   # dashboard web
    networks:
      - dask-net

  # 2) Les workers Dask
  worker:
    image: daskdev/dask:latest
    command: dask-worker tcp://scheduler:8786
    depends_on:
      - scheduler
    deploy:
      replicas: 3     # change à 4 ou 6 selon ton envie
    networks:
      - dask-net
    environment:
      # limite mémoire/cœurs si tu veux
      - EXTRA_APT_PACKAGES=
    # volumes: si tu utilises un volume pour partager les CSV

  # 3) Ton application, qui envoie le job
  app:
    build: .
    depends_on:
      - scheduler
      - worker
    environment:
      DASK_SCHEDULER_ADDRESS: "tcp://scheduler:8786"
    networks:
      - dask-net

networks:
  dask-net:
    driver: bridge
