services:
  # Dask Scheduler
  dask-scheduler:
    build: .
    container_name: dask-scheduler
    command: dask-scheduler
    ports:
      - "8786:8786"  # Port pour les workers
      - "8787:8787"  # Dashboard web
    networks:
      - dask-network
    environment:
      - DASK_SCHEDULER_ADDRESS=tcp://dask-scheduler:8786

  # Dask Worker 1
  dask-worker-1:
    build: .
    container_name: dask-worker-1
    command: dask-worker tcp://dask-scheduler:8786 --name worker-1 --nthreads 2 --memory-limit 2GB
    depends_on:
      - dask-scheduler
    networks:
      - dask-network
    environment:
      - DASK_SCHEDULER_ADDRESS=tcp://dask-scheduler:8786
    volumes:
      - ./data:/app/data:ro

  # Dask Worker 2
  dask-worker-2:
    build: .
    container_name: dask-worker-2
    command: dask-worker tcp://dask-scheduler:8786 --name worker-2 --nthreads 2 --memory-limit 2GB
    depends_on:
      - dask-scheduler
    networks:
      - dask-network
    environment:
      - DASK_SCHEDULER_ADDRESS=tcp://dask-scheduler:8786
    volumes:
      - ./data:/app/data:ro

  # Dask Worker 3
  dask-worker-3:
    build: .
    container_name: dask-worker-3
    command: dask-worker tcp://dask-scheduler:8786 --name worker-3 --nthreads 2 --memory-limit 2GB
    depends_on:
      - dask-scheduler
    networks:
      - dask-network
    environment:
      - DASK_SCHEDULER_ADDRESS=tcp://dask-scheduler:8786
    volumes:
      - ./data:/app/data:ro

  # Client - Application principale
  client:
    build: .
    container_name: dask-client
    command: python main.py
    depends_on:
      - dask-scheduler
      - dask-worker-1
      - dask-worker-2
      - dask-worker-3
    networks:
      - dask-network
    environment:
      - DASK_SCHEDULER_ADDRESS=tcp://dask-scheduler:8786
    volumes:
      - ./data:/app/data:ro
      - ./results:/app/results

networks:
  dask-network:
    driver: bridge